# Generated by Django 6.0.1 on 2026-02-12 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PastEvents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('ordering', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'past_events',
                'ordering': ['-date'],
            },
        ),
    ]
