# Generated by Django 6.0.1 on 2026-02-12 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('do_again_list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('past_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='do_again_list.pastevents')),
            ],
            options={
                'db_table': 'historical_event',
                'ordering': ['-saved_at'],
            },
        ),
    ]
