# Generated by Django 6.0.1 on 2026-02-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('do_again_list', '0007_pastevents_duration_and_max_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('xp', models.IntegerField(default=0)),
                ('gold', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('base_attack', models.IntegerField(default=1)),
                ('base_defense', models.IntegerField(default=0)),
                ('base_speed', models.IntegerField(default=1)),
                ('best_distance', models.IntegerField(default=0)),
                ('streak', models.IntegerField(default=0)),
                ('items', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'game_state',
            },
        ),
    ]
