# Generated by Django 6.0.1 on 2026-02-21 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('do_again_list', '0008_game_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastevents',
            name='value',
            field=models.FloatField(default=1.0),
        ),
    ]
