# Generated by Django 6.0.1 on 2026-02-24 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('do_again_list', '0010_gamestate_hero_hp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastevents',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
