# Generated by Django 6.0.1 on 2026-02-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('do_again_list', '0011_alter_pastevents_start_time_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastevents',
            name='repeats',
            field=models.BooleanField(default=True),
        ),
    ]
