# Generated by Django 6.0.1 on 2026-03-06 20:08

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('ordering', models.IntegerField(default=0)),
                ('default_duration', models.DurationField(default=datetime.timedelta(0))),
                ('next_time', models.DateTimeField(blank=True, null=True)),
                ('min_duration', models.DurationField(blank=True, null=True)),
                ('max_duration', models.DurationField(blank=True, null=True)),
                ('max_time_between_events', models.DurationField(blank=True, null=True)),
                ('min_time_between_events', models.DurationField(blank=True, null=True)),
                ('value', models.FloatField(default=1.0)),
                ('repeats', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp', models.IntegerField(default=0)),
                ('gold', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('base_attack', models.IntegerField(default=1)),
                ('base_defense', models.IntegerField(default=0)),
                ('base_speed', models.IntegerField(default=1)),
                ('best_distance', models.IntegerField(default=0)),
                ('streak', models.IntegerField(default=0)),
                ('items', models.JSONField(default=list)),
                ('hero_hp', models.IntegerField(default=-1)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Occurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurances', to='do_again_list.activity')),
            ],
            options={
                'ordering': ['-end_time'],
            },
        ),
    ]
