# Generated by Django 6.0.1 on 2026-03-08 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('do_again_list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamestate',
            name='best_distance',
        ),
        migrations.AddField(
            model_name='occurance',
            name='planned_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
