# Generated by Django 6.0.1 on 2026-02-12 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('do_again_list', '0002_historicalevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalevent',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='historicalevent',
            name='saved_at',
        ),
    ]
