# Generated by Django 6.0.1 on 2026-03-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('do_again_list', '0002_remove_gamestate_best_distance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_built_in',
            field=models.BooleanField(default=False, help_text='If True, this activity is a built-in that is automatically managed by the app.'),
        ),
    ]
