# Generated by Django 6.0.1 on 2026-03-12 10:58

from django.db import migrations, models


def populate_display_name(apps, schema_editor):
    Activity = apps.get_model('do_again_list', 'Activity')
    Activity.objects.filter(display_name='').update(display_name=models.F('title'))


class Migration(migrations.Migration):

    dependencies = [
        ('do_again_list', '0003_activity_is_built_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='code_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='display_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(populate_display_name, migrations.RunPython.noop),
    ]
