# Generated by Django 6.0.1 on 2026-03-15 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('do_again_list', '0005_gamestate_prestige'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestate',
            name='quest_tokens',
            field=models.IntegerField(default=0),
        ),
    ]
