# Generated by Django 6.0.2 on 2026-06-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('do_again_list', '0009_gamestate_bonus_xp'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='impulse_resisted_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activity',
            name='is_break',
            field=models.BooleanField(default=False),
        ),
    ]
