# Generated by Django 6.0.1 on 2026-02-24 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('do_again_list', '0012_pastevents_repeats'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastevents',
            name='next_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
