# Generated by Django 6.0.2 on 2026-03-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('do_again_list', '0013_pastevents_next_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PastEvents',
            new_name='PastEvent',
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='gamestate',
            table=None,
        ),
        migrations.AlterModelTable(
            name='historicalevent',
            table=None,
        ),
        migrations.AlterModelTable(
            name='pastevent',
            table=None,
        ),
    ]
