# Generated by Django 6.0.2 on 2026-03-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('do_again_list', '0014_rename_pastevents_pastevent_alter_gamestate_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
