# Generated by Django 6.0.2 on 2026-03-02 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('do_again_list', '0016_gamestate_owner_pastevent_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pastevent',
            options={},
        ),
        migrations.RemoveField(
            model_name='pastevent',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='pastevent',
            name='next_time',
        ),
        migrations.RemoveField(
            model_name='pastevent',
            name='start_time',
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='next_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pastevent',
            name='max_duration_between_events',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pastevent',
            name='min_duration_between_events',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='historicalevent',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__isnull', False), ('next_time__isnull', False), _connector='OR'), name='start_or_next_time_required'),
        ),
    ]
