# Generated by Django 6.0.2 on 2026-03-02 02:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('do_again_list', '0017_alter_pastevent_options_remove_pastevent_end_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PastEvent',
            new_name='Activity',
        ),
        migrations.RenameModel(
            old_name='HistoricalEvent',
            new_name='Occurance',
        ),
    ]
