# Generated by Django 6.0.2 on 2026-03-02 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('do_again_list', '0018_rename_pastevent_activity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='occurance',
            old_name='past_event',
            new_name='activity',
        ),
    ]
