# Generated by Django 6.0.2 on 2026-03-04 12:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('do_again_list', '0019_rename_past_event_occurance_activity'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='occurance',
            name='start_or_next_time_required',
        ),
        migrations.AddField(
            model_name='activity',
            name='next_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='occurance',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurances', to='do_again_list.activity'),
        ),
        migrations.AlterField(
            model_name='occurance',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RemoveField(
            model_name='occurance',
            name='next_time',
        ),
    ]
