# Generated by Django 6.0.2 on 2026-03-04 14:44

import datetime
from django.db import migrations, models
from do_again_list.utils import humanize_timedelta, parse_time_offset

migration_fields = [
    ("default_duration", "default_duration_td"),
    ("max_duration", "max_duration_td"),
    ("min_duration", "min_duration_td"),
    ("max_time_between_events", "max_duration_between_events"),
    ("min_time_between_events", "min_duration_between_events"),
]


def migrate_to_timedelta(apps, schema_editor):
    Activity = apps.get_model("do_again_list", "Activity")
    for activity in Activity.objects.all():
        for str_field, td_field in migration_fields:
            if (str_value := getattr(activity, str_field)) is not None:
                setattr(activity, td_field, parse_time_offset(str_value))
            else:
                setattr(activity, td_field, None)
        activity.save()


class Migration(migrations.Migration):
    dependencies = [
        ("do_again_list", "0020_remove_occurance_start_or_next_time_required_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="default_duration_td",
            field=models.DurationField(
                default=datetime.timedelta(0), verbose_name="temp5"
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="max_duration_td",
            field=models.DurationField(blank=True, null=True, verbose_name="temp2"),
        ),
        migrations.AddField(
            model_name="activity",
            name="min_duration_td",
            field=models.DurationField(blank=True, null=True, verbose_name="temp1"),
        ),
        migrations.AlterField(
            model_name="activity",
            name="max_duration_between_events",
            field=models.DurationField(blank=True, null=True, verbose_name="temp3"),
        ),
        migrations.AlterField(
            model_name="activity",
            name="min_duration_between_events",
            field=models.DurationField(blank=True, null=True, verbose_name="temp4"),
        ),
        migrations.RunPython(migrate_to_timedelta, migrations.RunPython.noop),
    ]
