# Generated by Django 6.0.2 on 2026-03-04 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('do_again_list', '0021_remove_activity_max_time_between_events_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='default_duration',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='max_duration',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='max_time_between_events',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='min_duration',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='min_time_between_events',
        ),
    ]
