# Generated by Django 6.0.2 on 2026-03-04 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('do_again_list', '0022_remove_activity_default_duration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='default_duration_td',
            new_name='default_duration',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='max_duration_td',
            new_name='max_duration',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='max_duration_between_events',
            new_name='max_time_between_events',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='min_duration_td',
            new_name='min_duration',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='min_duration_between_events',
            new_name='min_time_between_events',
        ),
    ]
