# Generated by Django 6.0.2 on 2026-03-04 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('do_again_list', '0023_rename_default_duration_td_activity_default_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='default_duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='activity',
            name='max_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='max_time_between_events',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='min_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='min_time_between_events',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
